### ISSUE TITLE
Run "sh -c node ./script/build.js" error, exit code 1

### ISSUE THREAD

**Issue by zhong914** [macacajs/macaca-android#59]
Downloading macaca-android to /usr/local/node-v6.10.2-linux-x64/lib/node_modules/macaca-android_tmp
Copying /usr/local/node-v6.10.2-linux-x64/lib/node_modules/macaca-android_tmp/._macaca-android@1.1.34@macaca-android to /usr/local/node-v6.10.2-linux-x64/lib/node_modules/macaca-android
Installing macaca-android's dependencies to /usr/local/node-v6.10.2-linux-x64/lib/node_modules/macaca-android/node_modules
[1/11] macaca-utils@~0.1.6 installed at node_modules/._macaca-utils@0.1.9@macaca-utils
[2/11] java-util@~0.1.0 installed at node_modules/._java-util@0.1.0@java-util
[3/11] temp@~0.8.3 installed at node_modules/._temp@0.8.3@temp
[4/11] android-unicode@1.0.11 installed at node_modules/._android-unicode@1.0.11@android-unicode
[5/11] webdriver-dfn-error-code@~1.0.1 installed at node_modules/._webdriver-dfn-error-code@1.0.4@webdriver-dfn-error-code
[6/11] driver-base@~0.1.0 installed at node_modules/._driver-base@0.1.4@driver-base
[7/11] xlogger@~1.0.0 installed at node_modules/._xlogger@1.0.6@xlogger
[8/11] unlock-apk@~0.1.11 installed at node_modules/._unlock-apk@0.1.16@unlock-apk
[9/11] uiautomator-client@1.1.9 installed at node_modules/._uiautomator-client@1.1.9@uiautomator-client
[10/11] macaca-adb@~1.0.3 installed at node_modules/._macaca-adb@1.0.22@macaca-adb
[11/11] macaca-chromedriver@~1.0.1 installed at node_modules/._macaca-chromedriver@1.0.30@macaca-chromedriver
execute post install 4 scripts...
[1/4] scripts.install android-unicode@1.0.11 run "node ./script/build.js"
JAVA_HOME is set to /usr/local/jdk1.8.0_131
Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp
Buildfile: /usr/local/node-v6.10.2-linux-x64/lib/node_modules/macaca-android/node_modules/._android-unicode@1.0.11@android-unicode/build.xml

BUILD FAILED
/usr/local/node-v6.10.2-linux-x64/lib/node_modules/macaca-android/node_modules/._android-unicode@1.0.11@android-unicode/build.xml:81: Cannot find /home/super7/Android/Sdk/tools/ant/build.xml imported from /usr/local/node-v6.10.2-linux-x64/lib/node_modules/macaca-android/node_modules/._android-unicode@1.0.11@android-unicode/build.xml

Total time: 0 seconds
Error: build failed
    at ChildProcess.<anonymous> (/usr/local/node-v6.10.2-linux-x64/lib/node_modules/macaca-android/node_modules/._ant-build@1.0.4@ant-build/lib/ant-build.js:111:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
/usr/local/node-v6.10.2-linux-x64/lib/node_modules/macaca-android/node_modules/._android-unicode@1.0.11@android-unicode/script/build.js:15
    throw e;
    ^

Error: build failed
    at ChildProcess.<anonymous> (/usr/local/node-v6.10.2-linux-x64/lib/node_modules/macaca-android/node_modules/._ant-build@1.0.4@ant-build/lib/ant-build.js:111:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
Install fail! Error: post install error, please remove node_modules before retry!
Run "sh -c node ./script/build.js" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node ./script/build.js" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/node-v6.10.2-linux-x64/lib/node_modules/cnpm/node_modules/runscript/index.js:65:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npminstall version: 2.29.1
npminstall args: /usr/local/node-v6.10.2-linux-x64/bin/node /usr/local/node-v6.10.2-linux-x64/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/home/super7/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org macaca-android -g --save

**Comment by xudafeng** [comment]
@zhong914 update version
